@startuml

title Client-APIService-GTS end to end,\nid_token in the wild

group Login/Bind Securely

group Login to IDP
Client_App -> Federated_IDP:Login
Client_App <- Federated_IDP:id_token
end
group Bind to Service
Client_App -> API_Service:Bind(id_token)
API_Service -> API_Service: validate id_token
API_Service -> Generic_STS: mint access_token
API_Service <- Generic_STS: access_token,etc
Client_App <- API_Service:id_token, access_token, refresh_token
end

group Make some API calls
Client_App -> API_Service:SomeApi:bearer:access_token
API_Service -> API_Service: validate access_token
Client_App <- API_Service: return data 
end
group Refresh
Client_App -> Generic_STS:refresh (refresh_token)
Client_App <- Generic_STS: access_token, refresh_token

end
@enduml
